### ISSUE TITLE
some Q-s:

### ISSUE THREAD

**Issue by mmmcorpsvit** [benoror/ember-postgrest-dynamic-ui#3]
its working on windows? 
why need server? 
can postgrest work without any web-server? for example direct from one index.html file?﻿

**Comment by benoror** [comment]
> its working on windows?

 It works on Windows x64, see: https://github.com/begriffs/postgrest/releases/tag/v0.4.0.0

> why need server?

You need a server to run PostgreSQL and PostgREST

> can postgrest work without any web-server? for example direct from one index.html file?﻿

If you mean something like nginx or Apache surely you can, Ember.js are just static (JS, HTML, CSS) files. Nevertheless you need a server for PostgreSQL and PostgREST
